# Generated by Django 6.0.2 on 2026-04-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_room_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_id',
        ),
    ]
