# Generated by Django 6.0.2 on 2026-04-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_remove_room_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='building_name',
            new_name='full_building_name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='full_room_name',
        ),
        migrations.AddField(
            model_name='building',
            name='short_building_name',
            field=models.CharField(default='Bruh', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='short_room_name',
            field=models.CharField(default='Bruh', max_length=10),
            preserve_default=False,
        ),
    ]
